### ISSUE TITLE
Scale consul using docker swarm

### ISSUE THREAD

**Issue by 13angs** [13angs/simple-ecom#5]
# Steps

## Deploy consul in cluster mode
- Join all the node
- Promote the node to Manager

```bash
docker node promote worker1
```
- Create a overlay attachable network

```bash
docker network create --driver=overlay --attachable se-prod-network
```

- create to folder in each node name `app`
  - group: devops
  - name: app
  - permission: sudo chmod 770
  - inherite permission: sudo chmod +s 
- copy the code to each node
- deploy the consul

## Notes
- need to use bridge network in order to connect between consul

## References
1. https://medium.com/hepsiburadatech/implementing-highly-available-rabbitmq-cluster-on-docker-swarm-using-consul-based-discovery-45c4e7919634
2. https://bhavik.io/2017/12/19/consul-with-docker-swarm-mode.html

**Comment by 13angs** [comment]
```bash
Failed to resolve se-prod-network: lookup se-prod-network on 127.0.0.11:53: server misbehaving
```

**Comment by 13angs** [comment]
```bash
cp: cannot create regular file 'config1.json': Permission denied
```

## References
1. https://unix.stackexchange.com/questions/466625/cp-cannot-create-regular-file-permission-denied

**Comment by 13angs** [comment]
## Attemps
1. create separate service for each consul server

**Comment by 13angs** [comment]
## Server setup
- install docker

**Comment by 13angs** [comment]
this error occur when using ip address

```bash
2022-11-12T15:57:02.413Z [WARN]  agent: Join cluster failed, will retry: cluster=LAN retry_interval=10s error="1 error occurred:
consul_consul.0.it3d8qr266xc@node-2    |        * Failed to join 172.104.161.244:8301: dial tcp 172.104.161.244:8301: connect: connection refused
```

**Comment by 13angs** [comment]
## Working method

- compose file

```yml
version: '3.8'
services:
  consul-server:
    image: consul:latest
    hostname: "{{.Node.Hostname}}"
    networks:
      - consul
      - prod
    ports:
      - 8400:8400
      - 8500:8500
      - 8600:53
    volumes:
      - consul-data:/consul/data
    deploy:
      mode: global
      placement:
        constraints: [node.labels.consul == true]
    command: [ "agent", "-server", "-bootstrap-expect=2", "-retry-max=3", "-retry-interval=10s", "-datacenter=prod", "-join=consul-server", "-retry-join=consul-server", "-bind={{ GetInterfaceIP \"eth0\" }}", "-client=0.0.0.0", "-ui"]
networks:
  consul:
  prod:
    external: true
volumes:
  consul-data:
```
